using Microsoft.AspNetCore.Mvc;
using ExamApp.Models;
using System.Collections.Generic;

namespace ExamApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var questions = new List<ExamQuestion>
            {
                new ExamQuestion { Number = 1, Category = "Relational Data Modeling", QuestionText = "What is the main problem solved by using a database instead of an in-memory collection?", OptionA = "It makes C# code shorter", OptionB = "It prevents the application from restarting", OptionC = "It allows data to persist after the application stops", OptionD = "It removes the need for MVC", CorrectAnswer = "C", Explanation = "Databases ensure data persistence beyond application life cycles." },
                new ExamQuestion { Number = 2, Category = "Relational Data Modeling", QuestionText = "Which approach is being used when an existing database is used to generate EF Core entity classes?", OptionA = "Code-First", OptionB = "Database-First", OptionC = "Model-First", OptionD = "Controller-First", CorrectAnswer = "B", Explanation = "Database-First generates code models from an existing schema." },
                new ExamQuestion { Number = 3, Category = "Relational Data Modeling", QuestionText = "What is the primary purpose of Entity Framework Core?", OptionA = "To create HTML pages automatically", OptionB = "To replace the MVC Controller", OptionC = "To map objects in code to relational database data", OptionD = "To replace the C# compiler", CorrectAnswer = "C", Explanation = "EF Core maps object models to relational tables." },
                new ExamQuestion { Number = 4, Category = "Relational Data Modeling", QuestionText = "Which EF Core component is primarily responsible for communicating with the database?", OptionA = "DbContext", OptionB = "DbSetView", OptionC = "ControllerContext", OptionD = "RazorContext", CorrectAnswer = "A", Explanation = "DbContext coordinates Entity Framework operations with the database." },
                new ExamQuestion { Number = 5, Category = "Relational Data Modeling", QuestionText = "What does the following command primarily do? dotnet ef dbcontext scaffold \"ConnectionString\" Microsoft.EntityFrameworkCore.SqlServer -o Models", OptionA = "Deletes the database", OptionB = "Creates a new MVC project", OptionC = "Generates EF Core models and a DbContext from an existing database", OptionD = "Starts the MVC application", CorrectAnswer = "C", Explanation = "Scaffolding creates entity models from a live database connection string." },
                new ExamQuestion { Number = 6, Category = "Conceptual Data Architecture", QuestionText = "Where is a database connection string commonly stored in an ASP.NET Core MVC application?", OptionA = "Program.cs only", OptionB = "appsettings.json", OptionC = "Index.cshtml", OptionD = "Student.cs", CorrectAnswer = "B", Explanation = "appsettings.json is the standard configuration repository for connection settings." },
                new ExamQuestion { Number = 7, Category = "Conceptual Data Architecture", QuestionText = "A Student belongs to exactly one Section, while a Section can contain many students. What type of relationship is this?", OptionA = "One-to-One", OptionB = "One-to-Many", OptionC = "Many-to-Many", OptionD = "Many-to-One only", CorrectAnswer = "B", Explanation = "A single section has multiple student entities associated with it." },
                new ExamQuestion { Number = 8, Category = "Conceptual Data Architecture", QuestionText = "In the following example, what is SectionId? public int SectionId { get; set; } public Section Section { get; set; }", OptionA = "Primary key of Student", OptionB = "Foreign key referencing Section", OptionC = "Navigation property", OptionD = "Database connection string", CorrectAnswer = "B", Explanation = "SectionId functions as the foreign key referencing the parent table." },
                new ExamQuestion { Number = 9, Category = "Conceptual Data Architecture", QuestionText = "What is the purpose of a navigation property such as public Section Section { get; set; }?", OptionA = "It stores the database password", OptionB = "It represents a relationship to another entity", OptionC = "It creates a new database", OptionD = "It validates the student's name", CorrectAnswer = "B", Explanation = "Navigation properties enable traversal between related model entities." },
                new ExamQuestion { Number = 10, Category = "Conceptual Data Architecture", QuestionText = "What does .Include() generally allow EF Core to do?", OptionA = "Delete the Section table", OptionB = "Load related Section data together with Students", OptionC = "Create a new Student", OptionD = "Validate Student input", CorrectAnswer = "B", Explanation = "Include() performs eager loading of related entity records." },
                new ExamQuestion { Number = 11, Category = "Data Normalization & Validation", QuestionText = "Why might a ViewModel be used when displaying Student and Section information?", OptionA = "To replace the database", OptionB = "To combine or shape the data specifically needed by the view", OptionC = "To automatically create database tables", OptionD = "To prevent controllers from using LINQ", CorrectAnswer = "B", Explanation = "ViewModels shape customized data structures tailored for the user interface." },
                new ExamQuestion { Number = 12, Category = "Data Normalization & Validation", QuestionText = "Consider this query: var students = _context.Students.Include(s => s.Section).ToList(); What is the main benefit of Include(s => s.Section)?", OptionA = "It loads the related Section navigation property", OptionB = "It creates a Section object manually", OptionC = "It removes the foreign key", OptionD = "It prevents the query from accessing the database", CorrectAnswer = "A", Explanation = "It ensures the related Section record is loaded alongside students." },
                new ExamQuestion { Number = 13, Category = "Data Normalization & Validation", QuestionText = "Which type of validation occurs in the browser before a request is sent to the server?", OptionA = "Database-level validation", OptionB = "Client-side validation", OptionC = "Server-side validation", OptionD = "EF Core migration validation", CorrectAnswer = "B", Explanation = "Client-side validation executes directly within the user browser." },
                new ExamQuestion { Number = 14, Category = "Data Normalization & Validation", QuestionText = "Why is server-side validation still necessary if client-side validation exists?", OptionA = "Client-side validation can be bypassed", OptionB = "Client-side validation automatically modifies the database", OptionC = "Server-side validation only works with SQLite", OptionD = "Client-side validation cannot display messages", CorrectAnswer = "A", Explanation = "Users can disable or bypass client validations, requiring server verification." },
                new ExamQuestion { Number = 15, Category = "Data Normalization & Validation", QuestionText = "A school requires every student to have a unique Student Number. Which rule best represents this requirement?", OptionA = "Student Number should always be nullable", OptionB = "Student Number should be unique", OptionC = "Student Number should always be the same", OptionD = "Student Number should contain only spaces", CorrectAnswer = "B", Explanation = "Uniqueness rules guarantee individual differentiation among student records." },
                new ExamQuestion { Number = 16, Category = "SQL & CRUD Operations", QuestionText = "Which is the best reason for having a database-level unique constraint on StudentNumber?", OptionA = "It protects data integrity even if application-level validation is bypassed", OptionB = "It makes Razor Views render faster", OptionC = "It removes the need for a Controller", OptionD = "It automatically creates a ViewModel", CorrectAnswer = "A", Explanation = "Database constraints act as a final safety barrier for data integrity." },
                new ExamQuestion { Number = 17, Category = "SQL & CRUD Operations", QuestionText = "What is the purpose of a try...catch block in a controller?", OptionA = "It creates navigation properties", OptionB = "To catch and handle exceptions that may occur during execution", OptionC = "To generate database tables", OptionD = "To perform client-side validation", CorrectAnswer = "B", Explanation = "Try-catch blocks intercept and manage runtime application exceptions." },
                new ExamQuestion { Number = 18, Category = "SQL & CRUD Operations", QuestionText = "Which middleware is commonly used in ASP.NET Core for centralized exception handling?", OptionA = "UseDatabase()", OptionB = "UseExceptionHandler()", OptionC = "UseValidationHandler()", OptionD = "UseMvcDatabase()", CorrectAnswer = "B", Explanation = "UseExceptionHandler provides centralized global error handling middleware." },
                new ExamQuestion { Number = 19, Category = "SQL & CRUD Operations", QuestionText = "A user requests /Student/999, but Student 999 does not exist. What would be the most appropriate response?", OptionA = "Display the student's information anyway", OptionB = "Display a Not Found (404) response/page", OptionC = "Delete Student 999", OptionD = "Create Student 999 automatically", CorrectAnswer = "B", Explanation = "A 404 Not Found response properly signals an unavailable resource." },
                new ExamQuestion { Number = 20, Category = "SQL & CRUD Operations", QuestionText = "A student already belongs to Section A for a particular subject. The application attempts to assign the same student to Section A again. What is the primary concern?", OptionA = "Data integrity", OptionB = "HTML formatting", OptionC = "CSS inheritance", OptionD = "Razor syntax", CorrectAnswer = "A", Explanation = "Duplicate assignments threaten the data integrity of records." }
            };

            return View(questions);
        }
    }
}